'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import Header from '@/components/dashboard/Header';
import Button from '@/components/ui/Button';
import LoadingSpinner from '@/components/ui/LoadingSpinner';

interface BriefStats {
  journalCount: number;
  documentCount: number;
  financialCount: number;
  timelineCount: number;
}

function buildPdfHtml(brief: string, generatedAt: string) {
  const escaped = brief.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return [
    '<!DOCTYPE html><html><head>',
    '<title>Full Situation Brief</title>',
    '<style>',
    'body{font-family:Georgia,"Times New Roman",serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.7}',
    '.header{border-bottom:2px solid #333;padding-bottom:16px;margin-bottom:24px}',
    '.header h1{font-size:22px;margin:0 0 4px 0}',
    '.header p{font-size:13px;color:#666;margin:2px 0}',
    '.brief{font-size:14px;white-space:pre-wrap}',
    '.disclaimer{margin-top:32px;padding-top:16px;border-top:1px solid #ccc;font-size:11px;color:#999;font-style:italic}',
    '@media print{body{margin:20px}}',
    '</style></head><body>',
    '<div class="header">',
    '<h1>Full Situation Brief</h1>',
    '<p>Confidential — Prepared for Professional Review</p>',
    `<p>Generated: ${generatedAt}</p>`,
    '</div>',
    `<div class="brief">${escaped}</div>`,
    '<div class="disclaimer">',
    'This is an AI-generated brief based on user-provided data. It should be reviewed for accuracy and completeness before being used in any legal or professional context. Generated by Divorce Companion.',
    '</div>',
    '</body></html>',
  ].join('');
}

export default function BriefPage() {
  const router = useRouter();
  const supabase = createClient();

  const [brief, setBrief] = useState<string | null>(null);
  const [stats, setStats] = useState<BriefStats | null>(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  // Fetch data counts so user can see what'll be included
  useEffect(() => {
    async function fetchCounts() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/login');
        return;
      }

      const [j, d, f, t] = await Promise.all([
        supabase.from('journal_entries').select('id', { count: 'exact', head: true }),
        supabase.from('documents').select('id', { count: 'exact', head: true }),
        supabase.from('financial_items').select('id', { count: 'exact', head: true }),
        supabase.from('timeline_events').select('id', { count: 'exact', head: true }),
      ]);

      setStats({
        journalCount: j.count || 0,
        documentCount: d.count || 0,
        financialCount: f.count || 0,
        timelineCount: t.count || 0,
      });
      setLoading(false);
    }

    fetchCounts();
  }, []);

  async function handleGenerate() {
    setGenerating(true);
    setError('');

    try {
      const res = await fetch('/api/brief/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || 'Failed to generate brief.');
        setGenerating(false);
        return;
      }

      setBrief(data.brief);
      setStats(data.stats);
      setGeneratedAt(new Date().toISOString());
    } catch {
      setError('Failed to generate brief. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  const handleCopy = async () => {
    if (!brief) return;
    await navigator.clipboard.writeText(brief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    if (!brief || !generatedAt) return;

    const generated = new Date(generatedAt).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    const html = buildPdfHtml(brief, generated);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const printWindow = window.open(url, '_blank');

    if (printWindow) {
      printWindow.addEventListener('afterprint', () => {
        URL.revokeObjectURL(url);
      });
      printWindow.addEventListener('load', () => {
        printWindow.print();
      });
    }
  };

  const totalItems = stats
    ? stats.journalCount + stats.documentCount + stats.financialCount + stats.timelineCount
    : 0;

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <Header />

      <main className="max-w-3xl mx-auto px-4 py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-zinc-900 dark:text-white">
            Full Situation Brief
          </h1>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
            Generate a comprehensive professional brief from all your data
          </p>
        </div>

        {/* Data overview cards */}
        {loading ? (
          <div className="flex justify-center py-12">
            <LoadingSpinner />
          </div>
        ) : (
          <>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
              <DataCard label="Journal Entries" count={stats?.journalCount || 0} href="/journal" />
              <DataCard label="Timeline Events" count={stats?.timelineCount || 0} href="/timeline" />
              <DataCard label="Financial Items" count={stats?.financialCount || 0} href="/finances" />
              <DataCard label="Documents" count={stats?.documentCount || 0} href="/vault" />
            </div>

            {/* Generate button or brief display */}
            {!brief ? (
              <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm p-8 text-center">
                {totalItems === 0 ? (
                  <>
                    <p className="text-zinc-500 dark:text-zinc-400 mb-2">
                      No data to generate a brief from yet.
                    </p>
                    <p className="text-sm text-zinc-400 dark:text-zinc-500">
                      Start by adding journal entries, timeline events, or financial items.
                    </p>
                  </>
                ) : (
                  <>
                    <p className="text-zinc-600 dark:text-zinc-300 mb-2">
                      AI will analyse <span className="font-semibold">{totalItems} items</span> across your journal, timeline, finances, and documents to generate a professional situation brief.
                    </p>
                    <p className="text-sm text-zinc-400 dark:text-zinc-500 mb-6">
                      This typically takes 15-30 seconds depending on how much data you have.
                    </p>

                    <Button onClick={handleGenerate} isLoading={generating}>
                      {generating ? 'Generating Brief...' : 'Generate Full Brief'}
                    </Button>

                    {generating && (
                      <p className="text-sm text-zinc-400 dark:text-zinc-500 mt-4 animate-pulse">
                        Analysing your data and generating a comprehensive brief...
                      </p>
                    )}
                  </>
                )}

                {error && (
                  <p className="mt-4 text-sm text-red-500">{error}</p>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                {/* Brief content */}
                <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm p-6">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-lg font-semibold text-zinc-900 dark:text-white">
                      Your Situation Brief
                    </h2>
                    {generatedAt && (
                      <span className="text-xs text-zinc-500 dark:text-zinc-400">
                        Generated {new Date(generatedAt).toLocaleDateString('en-GB', {
                          day: 'numeric',
                          month: 'short',
                          year: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </span>
                    )}
                  </div>

                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <p className="text-sm text-zinc-800 dark:text-zinc-200 whitespace-pre-wrap leading-relaxed">
                      {brief}
                    </p>
                  </div>

                  <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-4 italic">
                    This is an AI-generated brief. Please review carefully for accuracy before sharing with any professional.
                  </p>

                  {/* Actions */}
                  <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-zinc-200 dark:border-zinc-700">
                    <Button size="sm" variant="outline" onClick={handleCopy}>
                      {copied ? 'Copied!' : 'Copy Brief'}
                    </Button>
                    <Button size="sm" variant="outline" onClick={handleExportPDF}>
                      Export PDF
                    </Button>
                    <Button size="sm" variant="outline" onClick={handleGenerate} isLoading={generating}>
                      Regenerate
                    </Button>
                  </div>
                </div>

                {/* Data sources summary */}
                {stats && (
                  <div className="bg-zinc-100 dark:bg-zinc-800/50 rounded-lg p-4">
                    <p className="text-xs text-zinc-500 dark:text-zinc-400">
                      Brief generated from: {stats.journalCount} journal {stats.journalCount === 1 ? 'entry' : 'entries'}, {stats.timelineCount} timeline {stats.timelineCount === 1 ? 'event' : 'events'}, {stats.financialCount} financial {stats.financialCount === 1 ? 'item' : 'items'}, {stats.documentCount} {stats.documentCount === 1 ? 'document' : 'documents'}
                    </p>
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}

function DataCard({ label, count, href }: { label: string; count: number; href: string }) {
  return (
    <a
      href={href}
      className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm p-4 hover:border-zinc-300 dark:hover:border-zinc-700 transition-colors"
    >
      <p className="text-2xl font-bold text-zinc-900 dark:text-white">{count}</p>
      <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">{label}</p>
    </a>
  );
}
